service: deets
# app and org for use with dashboard.serverless.com
app: deets-app
org: shuaiscott

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: us-west-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

custom:
  pythonRequirements:
    dockerizePip: true
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_deets:
    handler: handler.get_deets
    events:
      - http:
          path: deets/{id}
          method: get
          request: 
            parameters: 
               paths: 
                 id: true
  create_deets:
    handler: handler.create_deets
    events:
      - http:
          path: deets
          method: post
  # update_deets:
  #   handler: handler.update_deets
  #   events:
  #     - http:
  #         path: deets
  #         method: put

plugins:
  - serverless-python-requirements
