name: Build and Deploy app
on:
  push:
    branches:
      - main
jobs:

# AWS Lambda Deploy Job
  aws-lambda-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./serverless
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Serverless Deploy
        run: npm run-script deploy-prod
        working-directory: ${{env.working-directory}}
        env: 
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  

# React Github Pages Deployment Jobs
  github-pages-build-and-deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./react
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        working-directory: ${{env.working-directory}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: react/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
